answers/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', include('admin_honeypot.urls', namespace='admin_honeypot')),
    path('stranger/', admin.site.urls),
    path("__reload__/", include("django_browser_reload.urls")),
    path("",include("app.urls")),
    path('accounts/', include('allauth.urls')),

]

app/urls.py
from django.urls import path,include
from . import views
urlpatterns = [
    path("",views.index,name="home"),
    path("answer/<question_id>",views.answer,name="answer"),
    path("create/",views.create,name="create"),
    path("about",views.about,name="about"),
    path("delete_question/<question_id>",views.delete_question,name="delete_question"),
]

app/models.py
from django.db import models
import uuid
from django.contrib.auth.models import User
# Create your models here.
class LangChoice(models.TextChoices):
    C = ("C","C")
    Cpp = ("C++","C++")
    Python = ("python","Python")
    Javascript = ("javascript","Javascript")
    Java = ("java","Java")
    Go = ("go","Go")
    Rust = ("rust","rust")

class Question(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE,null=True,blank=True)
    question = models.TextField()
    answer  = models.TextField()
    id = models.CharField(default=uuid.uuid4,max_length=100,primary_key=True,editable=False)
    language = models.CharField(choices=LangChoice,default="",max_length=110)
    uploaded_at = models.DateTimeField(auto_now_add=True,null=True,blank=True)
    def __str__(self):
        return f"{self.user}"
    

app/forms.py
from django import forms
from .models import *
class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = ["question","answer","language"]
        labels = {
            "language":"Select programming Language"
        }

        widgets = {
            "question": forms.Textarea(attrs={"class":"textarea card text-black  textarea-bordered bg-white  font-bold w-full","placeholder":"Enter the Question","style":"height: 7rem;"}),
            "answer": forms.Textarea(attrs={"class":"textarea text-black  textarea-bordered card  bg-white font-bold w-full  ","placeholder":"Enter the Answer","style":"height: 10rem;"}),
            "language" : forms.Select(attrs={"class":"text-black font-bold"})
        }

app/views.py
from django.shortcuts import HttpResponse,render,get_object_or_404,redirect
from django.http import JsonResponse
from .models import *
from .forms import *
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.contrib import messages
from pygments.lexers import guess_lexer
from pygments.util import ClassNotFound
import datetime 
# Create your views here.
def index(request):
    all_questions = Question.objects.all().order_by("uploaded_at")

    if request.method == "POST":
        word = request.POST.get("search")
        all_questions = Question.objects.filter(question__icontains=word)
        if not all_questions:
            messages.error(request,"Question not found")
            return redirect("home")

    paginator = Paginator(all_questions,5)
    page = int(request.GET.get("page",1))
    try:
        all_questions = paginator.page(page)
    except:
        return HttpResponse("")

    context = {
        "questions":all_questions,
        "page":page,
    }
    if request.headers.get("HX-Request"):
        return render(request,"infinite.html",context)
    return render(request,"index.html",context)

@login_required
def answer(request,question_id):
    q_and_a = get_object_or_404(Question,id=question_id)

    context = {
        "question":q_and_a
    }

    return render(request,"answer.html",context)

def about(request):

    return render(request,"about.html")

@login_required
def create(request):
    form =  QuestionForm()
    if request.method == "POST":
        form = QuestionForm(request.POST)
        if form.is_valid():
            data = form.save(commit=False)

            try:
                name = guess_lexer(data.answer)
                print(name.name)
            except ClassNotFound:
                print("it is not a programming language")
            if name.name != "Text only":
                data.user = request.user
                data.save()
                return redirect("answer",data.id)
            
            messages.error(request,"your input is  not programming language")
            return redirect("home")
    context = {
        "form":form
    }
    return render(request,"create.html",context)

def delete_question(request,question_id):
    question =  get_object_or_404(Question,id=question_id)
    question.delete()

    return redirect("home")

templates/about.html
{% extends "base.html" %}

{% block content %}
<main class="flex mt-5 justify-center capitalize">
<div class="card  w-4/5 text-gray-950 font-bold bg-white flex items-center ">
    <h1 class="text-4xl uppercase">About</h1>
    <p class='sm:text-2xl text-md  p-5'> we can use website to share our knowledge <br>
    Most of them were stuggling to solve SRM virutal lab question so here find answer for  that and <br>
    check how other solve program effiecently </p>
    <p class='text-2xl pb-5'>this page was created by <span><a class="underline text-blue-500" href="https://instagram.com/stranger.conf">Stranger</a></span>
    </p>
</div>
</main>

{% endblock content %}

templates/answer.html
{% extends "base.html" %}

{% block content %}
<main class="flex justify-center mt-5 ">
    <div class="bg-white card  gap-2 items-center">
        <h1 class="text-black font-bold sm:text-2xl text-md px-7 pt-7">{{ question.question }} <span class="text-gray-400 mt-5 px-5 block">by {{ question.user }}</span></h1>
        <h1 class="font-bold text-black text-2xl self-start mx-3 xl:ml-20">Answer:</h1>
        <h1 class="self-start mx-5 font-bold text-gray-400">Uploaded {{ question.uploaded_at|timesince }} ago</h1>
        <div class="flex flex-col gap-2 w-full">
            <button onclick="copyToClipboard()" class="self-end mr-3 px-5 py-2 bg-blue-500 text-white font-semibold rounded hover:bg-blue-600 transition-colors">
                Copy Answer
            </button>
            <div id="text"  class="md:text-xl xl:text-2xl  font-extrabold card  text-white px-11 mb-5 mx-5  p-5   bg-black">
            
                {{ question.answer|linebreaks }}
            </div>
            <a href="{% url "delete_question" question.id %}" class="btn btn-error self-end mb-5 mr-5 ">Delete</a>

        </div>
    </div>
</main>
{% endblock content %}

templates/base.html
{% load static tailwind_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="Strange Answers is used for sharing knowlegde">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=5.0">
    <link rel="icon" href="{% static "images/favicon.png" %}" type="image/x-icon">
    <script src="https://unpkg.com/htmx.org@2.0.3"></script>
    {% comment %} <script src="https://cdnjs.cloudflare.com/ajax/libs/alpinejs/2.8.2/cdn.min.js"></script> {% endcomment %}
    <title>Student's Answers</title>
    {% tailwind_css  %}
</head>
<body class="bg-gray-800">
    <header class="flex justify-between items-center text-gray-950 p-5 bg-gradient-to-r from-blue-500 to-cyan-500  w-full">
        <h1 class=" font-bold text-2xl" ><a href="{% url "home" %}">Student's Answers</a></h1>
        <nav >
            <ul class="flex gap-3 items-center hidden md:block ">
                <li class="btn btn-error  text-xl mr-2"><a href="{% url "create" %}">Create</a></li>
             
                <li class="btn  btn-primary text-xl mr-2"><a href="https://instagram.com/stranger.conf">Contact</a></li>
                <li class="btn  btn-secondary text-xl mr-2"><a href="{% url "about" %}">About</a></li>
                {% if user.is_authenticated %}
                <li class="btn btn-error  text-xl mr-2"><a href="{% url "account_logout" %}">Logout</a></li>

                {% else %}
                <li class="btn btn-warning  text-xl mr-2"><a href="{% url "account_login" %}">Login</a></li>
                <li class="btn btn-warning  text-xl mr-2"><a href="{% url "account_signup" %}">Signup</a></li>
                {% endif %}
            </ul>
        </nav>


        <nav class="md:hidden flex ">
            <li class="btn btn-error  text-xl mr-2"><a href="{% url "create" %}">Create</a></li>
          
            <img src="{% static "image/menus.png" %}" alt="" class="w-8" id="toggle" onclick="change()">
        </nav>

    </header>
{% if messages %}
<div class="flex justify-center card items-center bg-yellow-500 text-white font-bold p-7 m-5">
    {% for message in messages  %}
        <h1 class="md:text-2xl xl:text-4xl text-xl">{{message}}</h1>
    {% endfor %}
</div>
{% endif %}

    <div class="bg-gray-500">
        <nav>
            <ul class="flex gap-3 items-center flex-col justify-center p-3 " id="hidden-menu"  style="display: none; ">
                <li class="btn  btn-primary text-xl mr-2"><a href="https://instagram.com/stranger.conf">Contact</a></li>
                <li class="btn  btn-secondary text-xl mr-2"><a href="{% url "about" %}">About</a></li>
                {% if user.is_authenticated %}
                <li class="btn btn-error text-sm mr-2"><a href="{% url "account_logout" %}">Logout</a></li>
                {% else %}
                <li class="btn btn-info  text-sm mr-2"><a href="{% url "account_login" %}">Login</a></li>
                <li class="btn btn-warning  text-sm mr-2"><a href="{% url "account_signup" %}">Signup</a></li>
                {% endif %}
            </ul>
        </nav>
    </div>
    {% block content %}
    {% endblock content %}

<footer class="flex justify-end mt-5 bottom-0">
    <div class="bg-blue-500 w-full flex items-end justify-center text-white font-bold p-5">
        <h1>this page was created by <span><a class="underline" href="https://instagram.com/stranger.conf">Stranger</a></h1>
    </div>
</footer>

<script src="{% static "js/index.js" %}"></script>
</body>
</html>

templates/create.html
{% extends "base.html" %}

{% block content %}

<form action="" method="POST" class="flex flex-col justify-center items-center gap-5 w-full pt-5 mt-5">
    {% csrf_token %}
    <div class="w-4/5">
        <label for="id_question" class="text-white font-bold">Question</label>
    {{ form.question }}
    </div>

    <div class="w-4/5 ">
        <label for="id_answer" class="text-white font-bold">Answer</label>
        {{ form.answer }}
        </div>

    <div class="flex gap-3 w-4/5 sm:flex-row flex-col">
        <label for="language.id_for_label" class="text-white font-bold">{{ form.language.label }}</label>
        {{ form.language  }}
    </div>

    <button class="btn btn-success">Add</button>
</form>

{% endblock content %}

templates/index.html
{% extends "base.html" %}
{% load static tailwind_tags %}
{% tailwind_css %}

{% block content %}
<p class="card capitalize text-white text-center font-bold m-3">
    <span class="bg-red-500 w-14 ">NOTE:</span> this is website does not contain any answer because it is at starting stage. you can share you question and answer for 
    that. so your friends can learn to solve difficult problem and if you already solve a problem. you may see how other solve that 
    in low complexity and optimization way <span class="bg-red-500 ">(the wesbite may work and open slowly because it $0 budget project so all sever, database are setup on free tier with minimum spec)</span>
</p>
<form method="post" class="flex justify-center items-center   gap-2 mt-2">
    {% csrf_token %}
    <textarea type="text" name="search"placeholder="Search Here" id="" class="rounded-xl w-4/5 font-bold text-black"></textarea>
    <button class="btn btn-primary">Search</button>
</form>
{% comment %} content {% endcomment %}
{% include "question.html" %}
{% endblock content %}

templates/infinite.html
{% for question in questions  %}
<main class='flex justify-center mt-10 '>
    <div class="flex flex-col w-4/5 card bg-white  items-center ">
        <h1 class="p-8 text-black font-bold text-2xl xl:text-3xl sm:text-3xl">{{ question.question  }}</h1>
        <a href="{% url "answer" question.id %}" class='btn mb-5 max-w-sm items-center  text-white'> View answers </a>
    </div>
</main>
{% endfor %}
<div hx-get="{% url "home" %}?page={{ page|add:1 }}" hx-target="this" hx-swap="outerHTML" hx-trigger="revealed">
    
</div>

templates/question.html
{% load custom_filters %}
{% for question in questions  %}
<main class='flex justify-center mt-10 '>
    <div class="flex flex-col w-4/5 card sm:bg-white  items-center bg-yellow-500 ">
        <h1 class="p-8 text-black font-light text-md xl:text-3xl sm:text-2xl">{{ question.question|lower_words:100  }}</h1>

        <a href="{% url "answer" question.id %}" class='btn mb-5 btn-error  max-w-sm  items-center '> View answers </a>
    </div>
</main>
{% endfor %}
<div hx-get="{% url "home" %}?page={{ page|add:1 }}" hx-target="this" hx-swap="outerHTML" hx-trigger="revealed">
    
</div>